### ISSUE TITLE
日本語化のDiscordはもう入れないでしょうか？

### ISSUE THREAD

**Issue by omiyama** [Shakekan/msfsjp#3]
すみません、どこが掲示板かわからずここに書かせていただきました。
Discordの招待が期限切れになっているようですが、もう入れないのでしょうか？
もしよかったら招待していただきたく、よろしくおねがいします。
MSFS2020 のフライトトレーニングを日本語化（表示＋音声）して配布しています。

**Comment by Shakekan** [comment]
すみません！私としたことが...
先週Steamのほうでのリンクを更新したのですがこちらでもリンクを貼っていたのを失念しておりました。
以下期限なしリンクです。Read Meのほうでも更新しておきます。配布済みのv0.1内のRead Meは変更しません。
[https://discord.gg/rSsBPgE](https://discord.gg/rSsBPgE)
あと、日本語化翻訳の件についてDiscordのほうでDMさせていただいてもよろしいでしょうか？音声翻訳がどのようなものなのか興味があります。
